# Generated by Django 5.2.8 on 2025-11-22 21:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(help_text='Sixt booking reference provided by the user.', max_length=64, unique=True)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Raw booking data as returned by the Sixt API.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.JSONField(blank=True, default=dict, help_text='Evolving conversation state: preferences, dislikes, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(help_text='Booking this chat session is based on.', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='ai_engine.bookingcontext')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], help_text='Who sent the message.', max_length=20)),
                ('content', models.TextField(help_text='The text content of the message.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional extra info about this message.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_engine.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
